#!/bin/sh

#Script to manage connection with dynu and update the dns record with the new ip taken by ngrok
#Run dynu help, to see usage
#Written by UPC enthusiast

#DYNU_KEY=
DYNU_URL=https://api.dynu.com/v2/dns
DYNU_ID=8490924
DYNU_RECORD_ID=3517649

function getRecordData {

    curl -s -X GET $URL/$ID/record/$RECORD_ID \
	    -H "accept: application/json" \
	    -H "API-Key: $KEY"
}

function checkDNSPort {

    getRecordData | python -m json.tool | grep "port" | awk '{print $2}'
}

function updateDNSPort {

    getRecordData > test
    sed -i -e "s/$(checkDNSPort)/$(bash ngrokgetip | cut -d ":" -f 2)/g" test
    DATA="$(cat test)"

    echo "$DATA" | python -m json.tool
    curl -s -X POST $URL/$ID/record/$RECORD_ID \
    	-H "accept: application/json" \
    	-H "API-Key: $KEY" \
    	-H "Content-Type: application/json" \
    	-d "$DATA" | python -m json.tool
    echo "-----> DNS Populated"
}

function help {

    echo "Dynu function script:"
    echo "  >dynu getRecordData (get Dynu record data)"
    echo "  >dynu checkDNSPort (get dynu public port)"
    echo "  >dynu updateDNSPort (update dynu port to ngrok one)"
}
$@
